#ranyanhao@@wind-mobi.com 20151230 begin
ccflags-y += -I$(srctree)/drivers/misc/mediatek/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	+=  mmc3524x.o
#ranyanhao@@wind-mobi.com 20151230 end