## zhaozhensen@wind-mobi.com 20160217 begin

##include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-y += imx258_pdafotp.o
obj-y += imx258mipiraw_Sensor.o
## zhaozhensen@wind-mobi.com 20160217 end
