# zhangkaiyuan@wind-mobi.com 20161107 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += fl11281_hd720_dsi_vdo_hlt.o


# zhangkaiyuan@wind-mobi.com 20161107 end
